# Generated by Django 4.1.5 on 2023-01-31 13:51

from django.db import migrations, models
import webapp.models
import webapp.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, storage=webapp.utils.storage.OverwriteStorage(), upload_to=webapp.models.user_directory_path),
        ),
    ]
