# Generated by Django 4.1.4 on 2022-12-31 23:28

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to=webapp.models.user_directory_path),
        ),
    ]
