# Generated by Django 4.1.4 on 2023-01-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
